### ISSUE TITLE
Generate data using realistic workloads running in the CNIT cluster

### ISSUE THREAD

**Issue by zeineb-rejiba** [braine-project/WP3R#116]
In order to confirm whether our results would still hold when we switch to a real deployment, we need to use some realistic workloads in our tests. 
- [x] look for 3 dockerized applications which are similar to the UCs. 
- [x] create a config file that contains parameters such as how often are such workloads submitted, how long do they last...
- [x] create an automated script to submit the workloads based on the config defined in the previous step
- [x] create a scipt to submit inference requests that will be served by the deployed workloads
- [x] measure and store metrics 
- [ ] use these metrics in the RL state when evaluating our DRL model

**Comment by johmicrot** [comment]
- [ ] saved data csv rows will contain  [requested information] [ consumed resources] where the consumed resources are an average of the full pod lifetime

**Comment by johmicrot** [comment]
- [ ] currently I am randomly generating how long a pod should run, discuss with javad if it is preferred to move the pod run-time to the dataset csv

**Comment by johmicrot** [comment]
- [ ] There is a bug with the CPU request.  I was using the "limit" parameter to control the amount of resources a spiky cpu pod can use, but if we are including the request parameter, then we have a problem because the limit cannot be higher than the request.  I'll avoid this for now by not sending a CPU request for now, but later we need a better way to stress the CPU.

**Comment by johmicrot** [comment]
- [ ] there is a bug where if a pod isn't successfully submitted, then program crashes.  Fix this

**Comment by johmicrot** [comment]
We were not able to collect realistic data from the servers due running out of time, and additionally a lack of CPU frequency information on the server virtualization
