### ISSUE TITLE
Evaluate results of Pointer-Net

### ISSUE THREAD

**Issue by johmicrot** [braine-project/WP3R#117]

**Comment by javadch** [comment]
- [ ] Extended for 1-2 weeks
- [ ] The result should be reported in a document and the doc link should be provided here as a comment

**Comment by javadch** [comment]
should be closed on 21st March

**Comment by johmicrot** [comment]
The latest results are included here. 
[Pointernet Report.docx](https://github.com/braine-project/WP3R/files/11017040/Pointernet.Report.docx)
