### ISSUE TITLE
list potential issues/improvements associated with current custom scheduler deployment

### ISSUE THREAD

**Issue by zeineb-rejiba** [braine-project/WP3R#120]
- [x] find prometheus query for getting disk usage. Right now, we're using 0 to populate those fields. 
- [x] in `custom_plugin.go`, replace occurrences of snake case with camel case (to match golang convention)
- [x] use meaningful names instead of customplugin (this applies to the content of `custom_plugin.go` and k8s config files
- [x] normalize pod requests. Right now, we have incoming values like: 100 for CPU and 209715200 for memory.
- [x] remove unnecessary/debugging print statements in `custom_plugin.go`
- [x] redirect output from commands in bash scripts to a log file
- [x] retrieve correct q-value corresponding to node name. right now, it's returning the q-value of the node at index 0 in the list
- [x] improve description of prometheus prequisites
- [x] use config map to include prometheus base URL
- [x] replace `sudo -u braine` with a vairable that picks up the username
- [x] replace the branch of the `scheduler-plugins` submodule so that it points to v1.19

---
- [x] add proper processing when the number of feasible nodes is less than the total number of nodes in the cluster
- [ ] [figure out issue with v1.20 ](https://github.com/braine-project/WP3R/issues/119)
- [x] improve failure handling in `custom_plugin.go` (what if call to prometheus/inference service fails...)
- [ ] investigate if there is a better way than multiplying by a constant (5 currently) to deal with the issue that the score function expects an int
- [x] figure out why scheduler trainer fails when using a cluster of 2 nodes. 
- [ ] ~~check if we can use smaller docker images~~
- [x] support the case when prometheus is not running as a k8s service?
- [x] add check if saved NN architecture is the same that's defined in the config file

**Comment by johmicrot** [comment]
we were not able to "investigate if there is a better way than multiplying by a constant (5 currently) to deal with the issue that the score function expects an int"  or fix "figure out issue with v1.20 '
