### ISSUE TITLE
Evaluate the BARINE scheduler

### ISSUE THREAD

**Issue by javadch** [braine-project/WP3R#16]
- [x] Evaluate for correct functioning
- [x] Evaluate for scheduling optimization (to how extent it is better than the default scheduler w.r.t. its objectives): evaluate 1) against the baseline (K8s default scheduler) and 2) against the state-of-the-art
- [x] Evaluate for decision performance (speed of matching the workload with a node)

**Comment by johmicrot** [comment]
These metrics were included in the accepted CEC23 paper
