### ISSUE TITLE
Custom scheduler limitations

### ISSUE THREAD

**Issue by johmicrot** [braine-project/WP3R#196]
1) If jobs are to be scheduled onto the master node, I've noticed that when the master node becomes overloaded, it will stop reporting some system metrics via prometheus.

2) When working with requesting resources for a pod, if a request is higher than the machine is able to, the braine_rl_scheduling go file doesn't report the node.   In the below image, we have three nodes.  One machine is close to 100% cpu utilization, and pod is requesting more cpu resources than it has.   We can see the prescore state sucesfully scores all three nodes, but during the scoring phase, the full machine is not displayed in blue.  It's not clear why this is happening.  The expected value is the agent has one score per machine.
![image](https://user-images.githubusercontent.com/12132335/173838791-06cd2385-3327-45cb-a263-936bbdff0914.png)

**Comment by johmicrot** [comment]
I've added the scheduler limitation to a document, and will update the document accordingly when new limitations are found.

[Braine_scheduler_limitations.docx](https://github.com/braine-project/WP3R/files/10875359/Braine_scheduler_limitations.docx)

**Comment by javadch** [comment]
- [ ] add this to the model specification document under #216
