### ISSUE TITLE
Add readme to the modeltrainer_noaction section

### ISSUE THREAD

**Issue by johmicrot** [braine-project/WP3R#207]
currently https://github.com/braine-project/WP3R/tree/main/T33/scheduler/modeltrainer_noaction has no readme,  add that on how to run/train models.

**Comment by johmicrot** [comment]
This has been added, and is still in development.  I will leave it open for now as a reminder to add a couple more things, but it is essentially done

**Comment by javadch** [comment]
- [ ] Add enough and clear explanation to the README about the situation where the ML Model decides that NO node should/could be chosen. Which implied the model does not suggest any node for an incoming placement request.
- [ ] One integrated architectural figure showing all the models with the feasibility action
- [ ] Update the README

**Comment by johmicrot** [comment]
Updated in this commit 
9bf8497393103778721329173ebf851b1c646162

**Comment by javadch** [comment]
see   [Execution Flow Section](https://github.com/braine-project/WP3R#execution-flow)
