### ISSUE TITLE
Normalization of CPU metric

### ISSUE THREAD

**Issue by johmicrot** [braine-project/WP3R#212]
The measurement  cpu_user_seconds_total that Prometheus reports can be used with the field "idle" to determine how much a specific CPU core is used in a period of a second.  

The cpu_user_seconds_total doesn't take into account the CPU  frequency.  So a CPU with a high frequency can complete more operations in a given period of time.  So in a sense the frequency of a CPU is a representation of how much a CPU core can handle, so we will change the scaled CPU metric to be normalized by some specific maximum frequency. 
Perhaps the equation would be 
(utilization average over all cores in machine A)* (frequency of cpu cores) * (number of cpu cores in machine A) / ((max possible frequency) ( max possible cores))

Also look into if it's possible to calculate the FLOPS of a CPU by collecting metrics

**Comment by johmicrot** [comment]
Sean got back to me regarding the CPU frequency issue.  He stated

> On the cpufreq issue, while intel P states and CPC are enabled in the BIOS unfortunately it doesn’t look like it’s possible to pass through the exact CPU core frequency to the VM. This is because VMWare masks the real CPU performance counters as it doesn’t isolate VM’s to specific hardware CPU cores. This means that even if it did pass through cpufreq it wouldn’t be accurate to what’s really going on in the underlying CPU cores. As such while it does pass through the CPUID and extensions, it just keeps the CPU frequency fixed at the CPU’s normal max speed.
There are 2 options here
>1.  Monitor CPU load by percentage using /proc/stat, see [here](https://www.idnt.net/en-US/kb/941772),[ here](https://rosettacode.org/wiki/Linux_CPU_utilization), [here](https://www.baeldung.com/linux/total-process-cpu-usage), and[ here](https://stackoverflow.com/questions/23367857/accurate-calculation-of-cpu-usage-given-in-percentage-in-linux) for how you convert /proc/stat info to a more human readable format.
>2.  Wait for the EMDC prototype. The actual EMDC hardware will be Ubuntu on bare metal, so cpufreq will be available.

Regarding the two options Sean provided we have: 

Option1 - with "Monitor CPU load by percentage using /proc/stat"  isn't what we are looking for.  We are currenly doing that now, and wanted to use number of CPU cores, and the each core frequency as a means to make this scaling more accurate. 

Option2 - Looks like our only option, so we will wait for the EMDC hardware.

**Comment by javadch** [comment]
- At the moment there is a solution implemented using a static max FLOPS.
- If Sean provides a dynamic solution, the code should be revisited and updated to consider that via the telemetry and the DAA
-https://github.com/braine-project/WP3R/blob/000fe790b84a9f19ca12b9ec8b57a3563d3fbd39/T33/Scheduler/dataAcess/make_query.py#L86
