### ISSUE TITLE
AutoML Report

### ISSUE THREAD

**Issue by johmicrot** [braine-project/WP3R#214]
Reports for AutoML go here

**Comment by javadch** [comment]
- [ ] A report is needed that contains: The list of paramaters fed to AutoML, the best configuration obatined from AutoML and the effect of that best config on the performance of the scheduling model.
- [ ] All this should go into a technical report
- [ ] the link to the report should be here

**Comment by johmicrot** [comment]
[AutoML.Report.docx](https://github.com/braine-project/WP3R/files/10875303/AutoML.Report.docx)

Latest report with updates is here

**Comment by javadch** [comment]
- [ ] test with a laerger test set
- [ ] fix optimized parameters and relax one of them in any direction (lower or upper than the optimized value) and see a) if output is sensitive to the change and b) if overall score performace is getting better or worse.
- [ ] talk to the AutoML guys to find out an explanation or a solution
