### ISSUE TITLE
Integrate L2 and L1 scheduling 

### ISSUE THREAD

**Issue by johmicrot** [braine-project/WP3R#217]
- [x] make a fork at the moment (or a local copy)
- [x] in the fork rename it so L2 is in the name 
~~-[ ] inside the plugin remove any link to the current HTTP REST API (DAA and scheduler Inferencer)~~
~~- [ ] have the plugin reply with a list of zeros or nones for the plugins ( this was said during the meeting, but i think it should not be the case.  I don't think it should reply in the same manner that the Scheduler Inferencer is, as it will be scheduling jobs at specific locations)~~
~~- [ ] 	the plugin will have access to a config file, e.g. federation_members_list~~
- [ ] 	inside the federation_members_list are endpoint URL's, and credentials of other Kubernetes clusters
~~-[]pod comes to the plugin, looks at the list, picks one and re-submits the pod to the selected endpoint~~
- [x] 	posting of pods should be done with Kubernetes api controller

look at Kubernetes api controller documentation for posting a pod to Kubernetes api controller 
Additionally I can talk to Edgard marks from ECC (his code is on project github)
The plugin will acts as a router.  We are making L2 and L1, L2 could control many L1 clusters

**Comment by javadch** [comment]
add namespaces to the list of registered clusters. 
check the incoming pod for the namespace, if exist try to forward it to the matching cluster, if not use the default RR policy to send it to a cluster.

**Comment by johmicrot** [comment]
added namespaces to the webhook config file at [webhook_config.yaml](https://github.com/braine-project/WP3R/blob/1fe75062fb40c44aa00c4632751e79071cce9a3f/T33/L2/webhook_docker/webhook_config.yaml)
incorporated the logic
- If pod namespace is found in config - forward it
-  elif reject policy is set - reject pod
-  else - use a cluster selection strategy

Had to move the L1 kubernets Service Agents to ClusterRole with ClusterRoleBinding in order to be able to create a pod/deployment under any namespace at the L1 stage.

**Comment by javadch** [comment]
- [ ] a complete user manual that explains how to create and submit a Pod to L2
- [ ] the user manual should also document the routing algorithm (round-robin) and the policies that govern the routing
- [ ] fix the namespace list in the config file to be a list per cluster and do the indexing in your code
- [ ] fix the issue with config file update needing to rebuild the image!

**Comment by johmicrot** [comment]
updates have been applied, just need to push branch  test_mutationwebhook to main.
