### ISSUE TITLE
Write D3.4 technical report 

### ISSUE THREAD

**Issue by javadch** [braine-project/WP3R#223]
- [x] Write the report (Javad)
- [x] Review and fix comments (John)
- [x] Final review (Javad)

[D3.4 Third report on the status of WP3-V1.01.docx](https://cnitpisa1-my.sharepoint.com/:w:/r/personal/admin_braine-project_eu/Documents/BRAINE/WP3/Deliverables/D3.4%20Third%20report%20on%20the%20status%20of%20WP3-V1.01.docx?d=w173e23c12f14453d9397885b7036539d&csf=1&web=1&e=3Eaar0)

**Comment by johmicrot** [comment]
V4 has been updated.
