### ISSUE TITLE
Include GPU requirements

### ISSUE THREAD

**Issue by zeineb-rejiba** [braine-project/WP3R#25]
We first have to check the UC descriptions whether this is a hard/soft requirement to make sure whether it's within the scope of the scorer or not.

**Comment by johmicrot** [comment]
We can add new resources by modifying the nodes directly. 
This can be done by typing "kubectl proxy" in one window and in another window type something like "curl --header "Content-Type: application/json-patch+json"   --request PATCH   --data '[{"op": "add", "path": "/status/capacity/example.com~1dongle", "value": "5"}]'   http://127.0.0.1:8001/api/v1/nodes/demo1-mast/status"
where "example.com~1dongle" is the name and "5" is the value.
1. Node exporter doesn't report the metric we need, but kube-state-metrics does report them
2. After installing kube-state-metrics, and making prometheus scrape kube-state-metrics, we can directly access the data in Influxdb through the DAA.
3.  Still being looked into
4. Pods can have the ability to request the new resources.  It's not clear to me now IF they need to or not.

**Comment by johmicrot** [comment]
Upon revisiting the incorrect document was attached,  the correct file has been added to the previous comment
