### ISSUE TITLE
Perform a comparison to 1-step greedy

### ISSUE THREAD

**Issue by zeineb-rejiba** [braine-project/WP3R#29]
This will tell us whether we need RL or if the agent is simply learning to be greedy.

**Comment by johmicrot** [comment]
we have implemented and compared the 1-step greedy.  Greed policy can be found at [model_helper_func.py](https://github.com/braine-project/WP3R/blob/main/T33/Scheduler/ModelTrainer/src/utils/model_helper_func.py)
