### ISSUE TITLE
Write  a paper on the BARINE's ML-based scheduler (FML-3-BRAINE)

### ISSUE THREAD

**Issue by javadch** [braine-project/WP3R#3]
- [ ] design purpose, scheduling objectives, algorithms, input parameters
- [ ] ML techniques, feature engineering, feature extraction/acquisition, 
- [ ] evaluation of the objective achievement, 
- [ ] compare with the baseline scheduler

Parallel with of #1 and #2 but publish after them 

Overleaf paper: https://www.overleaf.com/5392395372ytdhvnvztrns

**Comment by javadch** [comment]
move https://www.overleaf.com/project/640a33c34be51f98e7d62c3b 
to https://www.overleaf.com/5392395372ytdhvnvztrns

**Comment by javadch** [comment]
- [ ] the solution section should be in a stable state

**Comment by johmicrot** [comment]
The Solution Section is in a stable state.
